# Reduced-space design oracle: PEP value, gradient, and frozen-certificate
# curvature as functions of the policy parameters ω.

"""
Common interface for design objectives; implement
`eval_all(obj, ω; hess) -> (f, g, H, nsolves)`.
"""
abstract type AbstractDesignObjective end

"""
    DesignProblem(cp, policy, N; backend=MosekBackend())

Single-horizon parameterized design problem min_ω W(η(ω), N).
"""
struct DesignProblem{P<:AbstractPolicy,B<:SDPBackend} <: AbstractDesignObjective
    cp::CompiledPEP
    policy::P
    N::Int
    backend::B
end
DesignProblem(cp::CompiledPEP, policy::AbstractPolicy, N::Int;
              backend::SDPBackend = MosekBackend()) =
    DesignProblem(cp, policy, N, backend)

"""
    pep_value(dp, ω) -> (W, sol, η)

One SDP solve at the coefficients generated by the policy.
"""
function pep_value(dp::DesignProblem, ω::AbstractVector{<:Real})
    η, _, _ = evaluate_policy(dp.policy, ω, dp.N)
    sol = solve_pep(dp.cp, η; backend = dp.backend)
    return sol.obj, sol, η
end

"""
    pep_grad_hess(dp, ω, η, sol; hess=true) -> (gω, Hω)

Gradient and frozen-certificate curvature of W∘η at ω, reusing `sol`.
"""
function pep_grad_hess(dp::DesignProblem, ω::AbstractVector{<:Real},
                       η::AbstractVector{<:Real}, sol::PEPSolution;
                       hess::Bool = true)
    gη, Hη = grad_hess_eta(dp.cp, η, sol; hess)
    _, J, Hpol = evaluate_policy(dp.policy, ω, dp.N)
    return pullback(gη, Hη, J, hess ? Hpol : nothing)
end

"""One-shot value/gradient/curvature evaluation (1 SDP solve)."""
function eval_all(dp::DesignProblem, ω::AbstractVector{<:Real}; hess::Bool = true)
    W, sol, η = pep_value(dp, ω)
    g, H = pep_grad_hess(dp, ω, η, sol; hess)
    return W, g, H, 1
end
