# Reduced-space design oracle: PEP value, gradient, and frozen-certificate
# curvature as functions of the policy parameters ω.

"""
Common interface for design objectives; implement
`eval_all(obj, ω; hess) -> (f, g, H, nsolves)`.
"""
abstract type AbstractDesignObjective end

"""
    DesignProblem(cp, policy, N; backend=MosekBackend(),
                  facial_reduction=:none, fd_rel_step=1e-4)

Single-horizon parameterized design problem `min_ω W(η(ω), N)`.

With `facial_reduction=:explicit`, PEP values use exact partial facial
reduction and the first-order design gradient is a central finite difference
of certified reduced values. Frozen-certificate Hessians are intentionally
unavailable in this mode.
"""
struct DesignProblem{P<:AbstractPolicy,B<:SDPBackend} <: AbstractDesignObjective
    cp::CompiledPEP
    policy::P
    N::Int
    backend::B
    facial_reduction::Symbol
    fr_rtol::Float64
    fr_atol::Float64
    cert_tol::Float64
    gap_tol::Float64
    fd_rel_step::Float64
end

function DesignProblem(cp::CompiledPEP, policy::AbstractPolicy, N::Int;
                       backend::SDPBackend = MosekBackend(),
                       facial_reduction::Symbol = :none,
                       fr_rtol::Float64 = 1e-9,
                       fr_atol::Float64 = 1e-11,
                       cert_tol::Float64 = 1e-7,
                       gap_tol::Float64 = 1e-6,
                       fd_rel_step::Float64 = 1e-4)
    _check_facial_reduction_mode(facial_reduction)
    fd_rel_step > 0 || error("fd_rel_step must be positive")
    return DesignProblem(cp, policy, N, backend, facial_reduction, fr_rtol,
                         fr_atol, cert_tol, gap_tol, fd_rel_step)
end

# Preserve the previously supported positional backend constructor.
DesignProblem(cp::CompiledPEP, policy::AbstractPolicy, N::Int,
              backend::SDPBackend) =
    DesignProblem(cp, policy, N; backend)

supports_hessian(::AbstractDesignObjective) = true
supports_hessian(dp::DesignProblem) = dp.facial_reduction == :none

"""
    pep_value(dp, ω) -> (W, sol, η)

One SDP solve at the coefficients generated by the policy. An opt-in facially
reduced design refuses uncertified values instead of optimizing solver noise.
"""
function pep_value(dp::DesignProblem, ω::AbstractVector{<:Real})
    η, _, _ = evaluate_policy(dp.policy, ω, dp.N)
    sol = solve_pep(dp.cp, η; backend = dp.backend,
                    facial_reduction = dp.facial_reduction,
                    fr_rtol = dp.fr_rtol, fr_atol = dp.fr_atol,
                    cert_tol = dp.cert_tol, gap_tol = dp.gap_tol)
    if dp.facial_reduction != :none && !sol.diagnostics.certified
        error("facially reduced PEP value is not certified: " *
              "status=$(sol.status), primal=$(sol.diagnostics.primal_status), " *
              "dual=$(sol.diagnostics.dual_status), " *
              "gap=$(sol.diagnostics.relative_gap)")
    end
    return sol.obj, sol, η
end

"""
    pep_grad_hess(dp, ω, η, sol; hess=true) -> (gω, Hω)

Gradient and frozen-certificate curvature of `W∘η` at `ω`, reusing `sol`.
This dual-certificate route is available only without facial reduction;
`eval_all(...; hess=false)` supplies the certified finite-difference gradient
for facially reduced design.
"""
function pep_grad_hess(dp::DesignProblem, ω::AbstractVector{<:Real},
                       η::AbstractVector{<:Real}, sol::PEPSolution;
                       hess::Bool = true)
    dp.facial_reduction == :none ||
        error("pep_grad_hess is unavailable with facial reduction; call " *
              "eval_all(dp, ω; hess=false) for the finite-difference gradient")
    gη, Hη = grad_hess_eta(dp.cp, η, sol; hess)
    _, J, Hpol = evaluate_policy(dp.policy, ω, dp.N)
    return pullback(gη, Hη, J, hess ? Hpol : nothing)
end

function _facial_fd_gradient(dp::DesignProblem, ω::AbstractVector{<:Real})
    gradient = zeros(length(ω))
    for index in eachindex(ω)
        step = dp.fd_rel_step * max(1.0, abs(Float64(ω[index])))
        plus = collect(Float64, ω)
        minus = copy(plus)
        plus[index] += step
        minus[index] -= step
        Wplus, _, _ = pep_value(dp, plus)
        Wminus, _, _ = pep_value(dp, minus)
        gradient[index] = (Wplus - Wminus) / (2step)
    end
    return gradient
end

"""One-shot value/gradient/curvature evaluation."""
function eval_all(dp::DesignProblem, ω::AbstractVector{<:Real};
                  hess::Bool = true)
    W, sol, η = pep_value(dp, ω)
    if dp.facial_reduction != :none
        hess && error("frozen-certificate Hessians are unavailable with " *
                      "facial reduction; use design_fom, not design_som")
        gradient = _facial_fd_gradient(dp, ω)
        return W, gradient, zeros(0, 0), 1 + 2 * length(ω)
    end
    gradient, H = pep_grad_hess(dp, ω, η, sol; hess)
    return W, gradient, H, 1
end
